spring:
  application:
    name: medilab-doctor-service
  profiles:
    active: ${MEDILAB_PROFILE:dev}
server:
  port: ${DOCT_SERVICE_PORT:9099}
springdoc:
  swagger-ui:
    enabled: true
    path: /doctor-service-doc.html
  api-docs:
    enabled: true
    path: /doctor-service-api
user: 
 data:
  duplicate: 
    message: The Data submitted may have already existed. Please check the data and submit once again
---
spring:
  profiles: dev
  datasource:
    driver-class-name: ${MEDILAB_DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${MEDILAB_DB_URL:jdbc:mysql://localhost:3306/medilab-doctor-service}
    username: ${MEDILAB_DB_USER:root}
    password: ${MEDILAB_DB_PASSWORD:root}
  jpa:
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: stage
  h2:
    console:
      enabled: true
      path: /h2Console
